/**
 * ResiWalk - Services — HubSpot schema spec (Phase 0 provisioning).
 *
 * Declarative source of truth for the two new custom objects + the additive
 * Question properties. The provisioner (lib/hubspot → provisionServicesSchema)
 * reads this; a dry-run diffs it against HubSpot, apply creates what's missing.
 * Additive only — never touches existing inspection data. Names are neutral
 * (`service_*`); the internal codename never appears here.
 */
import { WORKTYPES } from './worktypes';

export interface PropSpec {
  name: string;
  label: string;
  type: string;        // string | number | date | datetime | bool | enumeration
  fieldType: string;   // text | textarea | number | date | booleancheckbox | select | checkbox
  options?: { label: string; value: string }[];
}

const opt = (pairs: [string, string][]) => pairs.map(([label, value]) => ({ label, value }));
const T = (name: string, label: string): PropSpec => ({ name, label, type: 'string', fieldType: 'text' });
const TA = (name: string, label: string): PropSpec => ({ name, label, type: 'string', fieldType: 'textarea' });
const NUM = (name: string, label: string): PropSpec => ({ name, label, type: 'number', fieldType: 'number' });
const DATE = (name: string, label: string): PropSpec => ({ name, label, type: 'date', fieldType: 'date' });
const DTIME = (name: string, label: string): PropSpec => ({ name, label, type: 'datetime', fieldType: 'date' });
const BOOL = (name: string, label: string): PropSpec => ({ name, label, type: 'bool', fieldType: 'booleancheckbox', options: opt([['Yes', 'true'], ['No', 'false']]) });
const SEL = (name: string, label: string, options: { label: string; value: string }[]): PropSpec => ({ name, label, type: 'enumeration', fieldType: 'select', options });

const WT_OPTS = WORKTYPES.map((w) => ({ label: w.label, value: w.id }));
const SUB_OPTS = [
  ...[...new Map(WORKTYPES.flatMap((w) => w.subtypes.map((s) => [s.id, s.label] as const))).entries()].map(([value, label]) => ({ label, value })),
  { label: 'Bid Item', value: 'bid_item' },   // vendor-requested additional work
];
const STATUS_OPTS = opt([['Estimated', 'estimated'], ['Assigned', 'assigned'], ['Submitted', 'submitted'], ['Review', 'review'], ['Completed', 'completed'], ['Canceled', 'canceled']]);
const SCOPE_OPTS = opt([['Property', 'property'], ['Community', 'community']]);
const OPERATOR_OPTS = opt([['is', 'is'], ['is any of', 'is any of'], ['is not', 'is not'], ['changes to', 'changes to'], ['is known', 'is known']]);

export interface ObjectSpec {
  name: string;                  // unique object name
  labels: { singular: string; plural: string };
  primaryDisplayProperty: string;
  envVar: string;                // env var that must hold the returned objectTypeId
  properties: PropSpec[];
}

export const SERVICE_OBJECT: ObjectSpec = {
  name: 'service_work_order',
  labels: { singular: 'Service Work Order', plural: 'Service Work Orders' },
  primaryDisplayProperty: 'service_name',
  envVar: 'HUBSPOT_SERVICE_TYPE_ID',
  properties: [
    T('service_name', 'Service Name'),
    SEL('worktype', 'Work Type', WT_OPTS),
    SEL('subtype', 'Subtype', SUB_OPTS),
    SEL('status', 'Status', STATUS_OPTS),
    BOOL('is_bid_item', 'Bid Item'),
    SEL('scope', 'Coverage Scope', SCOPE_OPTS),
    TA('service_description', 'Service Description'),
    DATE('due_date', 'Due Date'),
    T('region_snapshot', 'Region'),
    T('address_snapshot', 'Address'),
    T('locality_snapshot', 'Locality (City, ST ZIP)'),
    T('community_name', 'Community Name'),
    T('property_status_snapshot', 'Property Status'),
    NUM('latitude', 'Latitude'),
    NUM('longitude', 'Longitude'),
    NUM('vendor_cost', 'Vendor Cost'),
    NUM('markup_pct', 'Markup %'),
    NUM('client_cost', 'Client Cost'),
    NUM('vendor_cost_adjustment', 'Vendor Cost Adjustment'),
    T('vendor_cost_adjustment_reason', 'Adjustment Reason'),
    T('vendor_name', 'Assigned Vendor'),
    T('vendor_email', 'Vendor Email'),
    T('generated_by_rule_id', 'Generated By Rule'),
    T('enrollment_key', 'Enrollment Key'),
    BOOL('pet_stations', 'Pet Stations'),
    T('property_id_ref', 'Property Id Ref'),
    T('community_id_ref', 'Community Id Ref'),
    DTIME('submitted_at', 'Submitted At'),
    // The vendor-entered date the work was actually DONE (from the completion
    // form's "Service Completed Date"), distinct from submitted_at (when they hit
    // submit). The recurring-cadence engine anchors the next order on THIS date.
    DATE('service_completed_date', 'Service Completed Date'),
    SEL('ai_verdict', 'AI Verdict', opt([['Clean', 'clean'], ['Needs Review', 'needs_review']])),
    TA('ai_notes', 'AI Notes'),
    // Proof-of-service enrichment (vendor closed out with their own PDF report):
    // the AI's neutral summary of that document + the job photos extracted from
    // inside it. Both surface on the vendor/client service PDFs.
    TA('proof_summary', 'Proof-of-Service Summary'),
    TA('proof_photo_urls', 'Proof Photo URLs'),
    SEL('review_decision', 'Review Decision', opt([['Approved', 'approve'], ['Modified', 'modify'], ['Rejected', 'reject']])),
    TA('review_notes', 'Review Notes'),
    T('reviewed_by', 'Reviewed By'),
    DTIME('reviewed_at', 'Reviewed At'),
    DTIME('completed_at', 'Completed At'),
    BOOL('ontime', 'On Time'),
    TA('before_photo_urls', 'Before Photo URLs'),
    TA('after_photo_urls', 'After Photo URLs'),
    TA('pet_before_photo_urls', 'Pet Station Before Photo URLs'),
    TA('pet_after_photo_urls', 'Pet Station After Photo URLs'),
    TA('answers_json', 'Completion Answers (JSON)'),
    // Community grass-cut billing split (see RECURRING_SERVICES_PLAN.md). A master
    // community Grass Cut carries the covered property snapshot + per-property
    // rate; on close-out it splits into one property SWO each. `for_billing`
    // flips master→false / children→true so billing never double-counts.
    BOOL('for_billing', 'For Billing'),
    T('master_service_id', 'Master Service Id'),
    TA('covered_property_ids', 'Covered Property Ids (JSON)'),
    NUM('covered_property_count', 'Covered Property Count'),
    NUM('per_property_rate', 'Per Property Rate'),
    // Community grass-cut master: the common-area cut cost, folded into the master
    // total and prorated across the per-property billing children on split.
    NUM('common_area_cost', 'Common Area Cost'),
    DTIME('split_at', 'Split At'),
    // Grass-cut tier payouts, snapshotted from the rule at generation (property
    // grass cuts only). Submit resolves the payout from these by the answered
    // "grass height"; blank → the code defaults (45/60/90). See lib/services/grassPricing.
    NUM('grass_rate_standard', 'Grass Rate — Standard'),
    NUM('grass_rate_overgrown', 'Grass Rate — Overgrown'),
    NUM('grass_rate_heavy', 'Grass Rate — Heavy'),
  ],
};

export const SERVICE_RULE_OBJECT: ObjectSpec = {
  name: 'service_rule',
  labels: { singular: 'Service Rule', plural: 'Service Rules Engine' },
  primaryDisplayProperty: 'rule_name',
  envVar: 'HUBSPOT_SERVICE_RULE_TYPE_ID',
  properties: [
    T('rule_name', 'Rule Name'),
    BOOL('active', 'Active'),
    SEL('worktype', 'Work Type', WT_OPTS),
    SEL('subtype', 'Subtype', SUB_OPTS),
    SEL('scope', 'Coverage Scope', SCOPE_OPTS),
    BOOL('pet_stations', 'Pet Stations'),
    SEL('props_mode', 'Property Mode', opt([['All (future-inclusive)', 'all'], ['List (fixed)', 'list']])),
    NUM('vendor_cost', 'Vendor Cost'),
    NUM('markup_pct', 'Markup %'),
    // Community grass-cut only: include a common-area cut and its cost (folded into
    // the master total, prorated across the per-property children on split).
    BOOL('include_common_areas', 'Include Common Areas'),
    NUM('common_area_cost', 'Common Area Cost'),
    // Grass-cut tier payouts (property grass cuts only). Configured in the rule's
    // pricing section; generation stamps them onto each created service.
    NUM('grass_rate_standard', 'Grass Rate — Standard'),
    NUM('grass_rate_overgrown', 'Grass Rate — Overgrown'),
    NUM('grass_rate_heavy', 'Grass Rate — Heavy'),
    TA('vendors_json', 'Vendors (JSON)'),
    TA('service_description', 'Service Description'),
    BOOL('recurring', 'Recurring'),
    TA('cadences_json', 'Cadences (JSON)'),
    NUM('initial_due_days', 'First Order Due (days)'),
    TA('skip_months_json', 'No-Service Months (JSON)'),
    TA('included_props_json', 'Included Properties (JSON)'),
    TA('portfolios_json', 'Portfolios (JSON)'),
    TA('communities_json', 'Communities (JSON)'),
    TA('regions_json', 'Regions (JSON)'),
    T('enroll_field', 'Enroll Field'),
    SEL('enroll_op', 'Enroll Operator', OPERATOR_OPTS),
    T('enroll_value', 'Enroll Value'),
    TA('enroll_criteria_json', 'Enrollment Criteria (JSON)'),   // multiple criteria (source of truth)
    SEL('enroll_combinator', 'Enroll Combinator', opt([['All (AND)', 'and'], ['Any (OR)', 'or']])),
    DATE('start_date', 'Rule Start Date'),                      // dormant until this date
    NUM('start_delay_days', 'Enroll Delay (days)'),             // start N days after a target first qualifies

    BOOL('stop_enabled', 'Stop Enabled'),
    SEL('stop_mode', 'Stop Mode', opt([['Condition', 'condition'], ['Date', 'date'], ['Count', 'count']])),
    T('stop_field', 'Stop Field'),
    SEL('stop_op', 'Stop Operator', OPERATOR_OPTS),
    T('stop_value', 'Stop Value'),
    TA('stop_criteria_json', 'Stop Criteria (JSON)'),           // multiple criteria (source of truth)
    SEL('stop_combinator', 'Stop Combinator', opt([['All (AND)', 'and'], ['Any (OR)', 'or']])),
    DATE('stop_date', 'Stop Date'),
    NUM('stop_count', 'Stop After N Services'),
  ],
};

// Additive properties on the REUSED inspection Question object (keys a form to a
// service worktype+subtype; carries price effects + follow-up trigger config).
export const QUESTION_ADDITIONS: PropSpec[] = [
  SEL('service_worktype', 'Service Work Type', WT_OPTS),
  SEL('service_subtype', 'Service Subtype', SUB_OPTS),
  TA('choice_price_json', 'Choice Price Effects (JSON)'),
  TA('trigger_json', 'Follow-Up Trigger (JSON)'),
];

export const SERVICE_OBJECTS: ObjectSpec[] = [SERVICE_OBJECT, SERVICE_RULE_OBJECT];

// Association definitions to create (labeled v4 associations).
// `to` is a token resolved at apply time: PROPERTY | COMPANY | COMMUNITY | service | service_rule.
export const SERVICE_ASSOCIATIONS: { from: string; to: string; name: string; label: string }[] = [
  { from: 'service_work_order', to: 'PROPERTY', name: 'service_to_property', label: 'Service → Property' },
  { from: 'service_work_order', to: 'COMMUNITY', name: 'service_to_community', label: 'Service → Community' },
  { from: 'service_work_order', to: 'COMPANY', name: 'service_to_vendor', label: 'Service → Vendor' },
  { from: 'service_work_order', to: 'service_rule', name: 'service_to_rule', label: 'Service → Rule' },
  { from: 'service_rule', to: 'PROPERTY', name: 'rule_to_property', label: 'Rule → Property' },
  { from: 'service_rule', to: 'COMMUNITY', name: 'rule_to_community', label: 'Rule → Community' },
  { from: 'service_rule', to: 'COMPANY', name: 'rule_to_vendor', label: 'Rule → Vendor' },
];
