"""
Phase 4, Step 2: Add the Tenant Chargeback Import (xlsx) URL property.

The finalize flow now produces a 5th deliverable: a Tenant Chargeback Import
file in xlsx format, formatted for direct upload into the property management
system. Stored on the inspection record like the other PDF URLs.

This script is idempotent. Re-run to confirm the property exists.

Usage:
    python phase4_step2_add_chargeback_xlsx_url.py
"""

from __future__ import annotations
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'rate_card_phase1'))
from _hubspot_helpers import ensure_property  # type: ignore

INSPECTION = "inspection"


def main():
    print("=" * 70)
    print("Phase 4, Step 2: Add Tenant Chargeback Import (xlsx) URL property")
    print("=" * 70)

    ensure_property(
        INSPECTION,
        "pdf_chargeback_xlsx_url",
        "PDF — Tenant Chargeback Import (xlsx) URL",
        type="string",
        field_type="text",
        group_name="pdf_outputs",
        description=(
            "URL of the Tenant Chargeback xlsx import file. Generated by the "
            "finalize flow alongside the PDFs. Blank when there are no "
            "chargeback lines on the inspection."
        ),
    )

    print("\n[done] pdf_chargeback_xlsx_url is ready on inspection.")


if __name__ == '__main__':
    main()
